#Aws DB and Jpa and Jwt and debug setting
spring:
  server:
    port: 8080
    servlet:
      encoding:
        force-response: true

  # db
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${LOCAL_DB_URL}?rewriteBatchedStatements=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}

  # jpa
  jpa:
    # auto create schema
    hibernate:
      ddl-auto: create
    # show sql query
    show-sql: true
    # SQL pretty print
    properties:
      hibernate:
        format_sql: true
    # colorful console
    output:
      ansi:
        enabled: always
    # initialize database data
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  # redis
  data:
    redis:
      host: localhost
      port: 6379

  # jwt
  jwt:
    secret: test16235116521431621113212311633
    token:
      access-expiration-time: 1_800_000   # 30m
      refresh-expiration-time: 9_000_000  # 6h

## logging above debugs
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
